export const COUNTRIES = () => [
  { label: 'Afghanistan', value: 'Afghanistan', countryCode: 'AF' },
  { label: 'Åland Islands', value: 'Åland Islands', countryCode: 'AX' },
  { label: 'Albania', value: 'Albania', countryCode: 'AL' },
  { label: 'Algeria', value: 'Algeria', countryCode: 'DZ' },
  { label: 'American Samoa', value: 'American Samoa', countryCode: 'AS' },
  { label: 'AndorrA', value: 'AndorrA', countryCode: 'AD' },
  { label: 'Angola', value: 'Angola', countryCode: 'AO' },
  { label: 'Anguilla', value: 'Anguilla', countryCode: 'AI' },
  { label: 'Antarctica', value: 'Antarctica', countryCode: 'AQ' },
  {
    label: 'Antigua and Barbuda',
    value: 'Antigua and Barbuda',
    countryCode: 'AG',
  },
  { label: 'Argentina', value: 'Argentina', countryCode: 'AR' },
  { label: 'Armenia', value: 'Armenia', countryCode: 'AM' },
  { label: 'Aruba', value: 'Aruba', countryCode: 'AW' },
  { label: 'Australia', value: 'Australia', countryCode: 'AU' },
  { label: 'Austria', value: 'Austria', countryCode: 'AT' },
  { label: 'Azerbaijan', value: 'Azerbaijan', countryCode: 'AZ' },
  { label: 'Bahamas', value: 'Bahamas', countryCode: 'BS' },
  { label: 'Bahrain', value: 'Bahrain', countryCode: 'BH' },
  { label: 'Bangladesh', value: 'Bangladesh', countryCode: 'BD' },
  { label: 'Barbados', value: 'Barbados', countryCode: 'BB' },
  { label: 'Belarus', value: 'Belarus', countryCode: 'BY' },
  { label: 'Belgium', value: 'Belgium', countryCode: 'BE' },
  { label: 'Belize', value: 'Belize', countryCode: 'BZ' },
  { label: 'Benin', value: 'Benin', countryCode: 'BJ' },
  { label: 'Bermuda', value: 'Bermuda', countryCode: 'BM' },
  { label: 'Bhutan', value: 'Bhutan', countryCode: 'BT' },
  { label: 'Bolivia', value: 'Bolivia', countryCode: 'BO' },
  {
    label: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
    countryCode: 'BA',
  },
  { label: 'Botswana', value: 'Botswana', countryCode: 'BW' },
  { label: 'Bouvet Island', value: 'Bouvet Island', countryCode: 'BV' },
  { label: 'Brazil', value: 'Brazil', countryCode: 'BR' },
  {
    label: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
    countryCode: 'IO',
  },
  { label: 'Brunei Darussalam', value: 'Brunei Darussalam', countryCode: 'BN' },
  { label: 'Bulgaria', value: 'Bulgaria', countryCode: 'BG' },
  { label: 'Burkina Faso', value: 'Burkina Faso', countryCode: 'BF' },
  { label: 'Burundi', value: 'Burundi', countryCode: 'BI' },
  { label: 'Cambodia', value: 'Cambodia', countryCode: 'KH' },
  { label: 'Cameroon', value: 'Cameroon', countryCode: 'CM' },
  { label: 'Canada', value: 'Canada', countryCode: 'CA' },
  { label: 'Cape Verde', value: 'Cape Verde', countryCode: 'CV' },
  { label: 'Cayman Islands', value: 'Cayman Islands', countryCode: 'KY' },
  {
    label: 'Central African Republic',
    value: 'Central African Republic',
    countryCode: 'CF',
  },
  { label: 'Chad', value: 'Chad', countryCode: 'TD' },
  { label: 'Chile', value: 'Chile', countryCode: 'CL' },
  { label: 'China', value: 'China', countryCode: 'CN' },
  { label: 'Christmas Island', value: 'Christmas Island', countryCode: 'CX' },
  {
    label: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
    countryCode: 'CC',
  },
  { label: 'Colombia', value: 'Colombia', countryCode: 'CO' },
  { label: 'Comoros', value: 'Comoros', countryCode: 'KM' },
  { label: 'Congo', value: 'Congo', countryCode: 'CG' },
  {
    label: 'Congo, The Democratic Republic of the',
    value: 'Congo, The Democratic Republic of the',
    countryCode: 'CD',
  },
  { label: 'Cook Islands', value: 'Cook Islands', countryCode: 'CK' },
  { label: 'Costa Rica', value: 'Costa Rica', countryCode: 'CR' },
  { label: "Cote D'Ivoire", value: "Cote D'Ivoire", countryCode: 'CI' },
  { label: 'Croatia', value: 'Croatia', countryCode: 'HR' },
  { label: 'Cuba', value: 'Cuba', countryCode: 'CU' },
  { label: 'Cyprus', value: 'Cyprus', countryCode: 'CY' },
  { label: 'Czech Republic', value: 'Czech Republic', countryCode: 'CZ' },
  { label: 'Denmark', value: 'Denmark', countryCode: 'DK' },
  { label: 'Djibouti', value: 'Djibouti', countryCode: 'DJ' },
  { label: 'Dominica', value: 'Dominica', countryCode: 'DM' },
  {
    label: 'Dominican Republic',
    value: 'Dominican Republic',
    countryCode: 'DO',
  },
  { label: 'Ecuador', value: 'Ecuador', countryCode: 'EC' },
  { label: 'Egypt', value: 'Egypt', countryCode: 'EG' },
  { label: 'El Salvador', value: 'El Salvador', countryCode: 'SV' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea', countryCode: 'GQ' },
  { label: 'Eritrea', value: 'Eritrea', countryCode: 'ER' },
  { label: 'Estonia', value: 'Estonia', countryCode: 'EE' },
  { label: 'Ethiopia', value: 'Ethiopia', countryCode: 'ET' },
  {
    label: 'Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
    countryCode: 'FK',
  },
  { label: 'Faroe Islands', value: 'Faroe Islands', countryCode: 'FO' },
  { label: 'Fiji', value: 'Fiji', countryCode: 'FJ' },
  { label: 'Finland', value: 'Finland', countryCode: 'FI' },
  { label: 'France', value: 'France', countryCode: 'FR' },
  { label: 'French Guiana', value: 'French Guiana', countryCode: 'GF' },
  { label: 'French Polynesia', value: 'French Polynesia', countryCode: 'PF' },
  {
    label: 'French Southern Territories',
    value: 'French Southern Territories',
    countryCode: 'TF',
  },
  { label: 'Gabon', value: 'Gabon', countryCode: 'GA' },
  { label: 'Gambia', value: 'Gambia', countryCode: 'GM' },
  { label: 'Georgia', value: 'Georgia', countryCode: 'GE' },
  { label: 'Germany', value: 'Germany', countryCode: 'DE' },
  { label: 'Ghana', value: 'Ghana', countryCode: 'GH' },
  { label: 'Gibraltar', value: 'Gibraltar', countryCode: 'GI' },
  { label: 'Greece', value: 'Greece', countryCode: 'GR' },
  { label: 'Greenland', value: 'Greenland', countryCode: 'GL' },
  { label: 'Grenada', value: 'Grenada', countryCode: 'GD' },
  { label: 'Guadeloupe', value: 'Guadeloupe', countryCode: 'GP' },
  { label: 'Guam', value: 'Guam', countryCode: 'GU' },
  { label: 'Guatemala', value: 'Guatemala', countryCode: 'GT' },
  { label: 'Guernsey', value: 'Guernsey', countryCode: 'GG' },
  { label: 'Guinea', value: 'Guinea', countryCode: 'GN' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau', countryCode: 'GW' },
  { label: 'Guyana', value: 'Guyana', countryCode: 'GY' },
  { label: 'Haiti', value: 'Haiti', countryCode: 'HT' },
  {
    label: 'Heard Island and Mcdonald Islands',
    value: 'Heard Island and Mcdonald Islands',
    countryCode: 'HM',
  },
  {
    label: 'Holy See (Vatican City State)',
    value: 'Holy See (Vatican City State)',
    countryCode: 'VA',
  },
  { label: 'Honduras', value: 'Honduras', countryCode: 'HN' },
  { label: 'Hong Kong', value: 'Hong Kong', countryCode: 'HK' },
  { label: 'Hungary', value: 'Hungary', countryCode: 'HU' },
  { label: 'Iceland', value: 'Iceland', countryCode: 'IS' },
  { label: 'India', value: 'India', countryCode: 'IN' },
  { label: 'Indonesia', value: 'Indonesia', countryCode: 'ID' },
  {
    label: 'Iran, Islamic Republic Of',
    value: 'Iran, Islamic Republic Of',
    countryCode: 'IR',
  },
  { label: 'Iraq', value: 'Iraq', countryCode: 'IQ' },
  { label: 'Ireland', value: 'Ireland', countryCode: 'IE' },
  { label: 'Isle of Man', value: 'Isle of Man', countryCode: 'IM' },
  { label: 'Israel', value: 'Israel', countryCode: 'IL' },
  { label: 'Italy', value: 'Italy', countryCode: 'IT' },
  { label: 'Jamaica', value: 'Jamaica', countryCode: 'JM' },
  { label: 'Japan', value: 'Japan', countryCode: 'JP' },
  { label: 'Jersey', value: 'Jersey', countryCode: 'JE' },
  { label: 'Jordan', value: 'Jordan', countryCode: 'JO' },
  { label: 'Kazakhstan', value: 'Kazakhstan', countryCode: 'KZ' },
  { label: 'Kenya', value: 'Kenya', countryCode: 'KE' },
  { label: 'Kiribati', value: 'Kiribati', countryCode: 'KI' },
  {
    label: "Korea, Democratic People'S Republic of",
    value: "Korea, Democratic People'S Republic of",
    countryCode: 'KP',
  },
  {
    label: 'Korea, Republic of',
    value: 'Korea, Republic of',
    countryCode: 'KR',
  },
  { label: 'Kuwait', value: 'Kuwait', countryCode: 'KW' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan', countryCode: 'KG' },
  {
    label: "Lao People'S Democratic Republic",
    value: "Lao People'S Democratic Republic",
    countryCode: 'LA',
  },
  { label: 'Latvia', value: 'Latvia', countryCode: 'LV' },
  { label: 'Lebanon', value: 'Lebanon', countryCode: 'LB' },
  { label: 'Lesotho', value: 'Lesotho', countryCode: 'LS' },
  { label: 'Liberia', value: 'Liberia', countryCode: 'LR' },
  {
    label: 'Libyan Arab Jamahiriya',
    value: 'Libyan Arab Jamahiriya',
    countryCode: 'LY',
  },
  { label: 'Liechtenstein', value: 'Liechtenstein', countryCode: 'LI' },
  { label: 'Lithuania', value: 'Lithuania', countryCode: 'LT' },
  { label: 'Luxembourg', value: 'Luxembourg', countryCode: 'LU' },
  { label: 'Macao', value: 'Macao', countryCode: 'MO' },
  {
    label: 'Macedonia, The Former Yugoslav Republic of',
    value: 'Macedonia, The Former Yugoslav Republic of',
    countryCode: 'MK',
  },
  { label: 'Madagascar', value: 'Madagascar', countryCode: 'MG' },
  { label: 'Malawi', value: 'Malawi', countryCode: 'MW' },
  { label: 'Malaysia', value: 'Malaysia', countryCode: 'MY' },
  { label: 'Maldives', value: 'Maldives', countryCode: 'MV' },
  { label: 'Mali', value: 'Mali', countryCode: 'ML' },
  { label: 'Malta', value: 'Malta', countryCode: 'MT' },
  { label: 'Marshall Islands', value: 'Marshall Islands', countryCode: 'MH' },
  { label: 'Martinique', value: 'Martinique', countryCode: 'MQ' },
  { label: 'Mauritania', value: 'Mauritania', countryCode: 'MR' },
  { label: 'Mauritius', value: 'Mauritius', countryCode: 'MU' },
  { label: 'Mayotte', value: 'Mayotte', countryCode: 'YT' },
  { label: 'Mexico', value: 'Mexico', countryCode: 'MX' },
  {
    label: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
    countryCode: 'FM',
  },
  {
    label: 'Moldova, Republic of',
    value: 'Moldova, Republic of',
    countryCode: 'MD',
  },
  { label: 'Monaco', value: 'Monaco', countryCode: 'MC' },
  { label: 'Mongolia', value: 'Mongolia', countryCode: 'MN' },
  { label: 'Montserrat', value: 'Montserrat', countryCode: 'MS' },
  { label: 'Morocco', value: 'Morocco', countryCode: 'MA' },
  { label: 'Mozambique', value: 'Mozambique', countryCode: 'MZ' },
  { label: 'Myanmar', value: 'Myanmar', countryCode: 'MM' },
  { label: 'Namibia', value: 'Namibia', countryCode: 'NA' },
  { label: 'Nauru', value: 'Nauru', countryCode: 'NR' },
  { label: 'Nepal', value: 'Nepal', countryCode: 'NP' },
  { label: 'Netherlands', value: 'Netherlands', countryCode: 'NL' },
  {
    label: 'Netherlands Antilles',
    value: 'Netherlands Antilles',
    countryCode: 'AN',
  },
  { label: 'New Caledonia', value: 'New Caledonia', countryCode: 'NC' },
  { label: 'New Zealand', value: 'New Zealand', countryCode: 'NZ' },
  { label: 'Nicaragua', value: 'Nicaragua', countryCode: 'NI' },
  { label: 'Niger', value: 'Niger', countryCode: 'NE' },
  { label: 'Nigeria', value: 'Nigeria', countryCode: 'NG' },
  { label: 'Niue', value: 'Niue', countryCode: 'NU' },
  { label: 'Norfolk Island', value: 'Norfolk Island', countryCode: 'NF' },
  {
    label: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
    countryCode: 'MP',
  },
  { label: 'Norway', value: 'Norway', countryCode: 'NO' },
  { label: 'Oman', value: 'Oman', countryCode: 'OM' },
  { label: 'Pakistan', value: 'Pakistan', countryCode: 'PK' },
  { label: 'Palau', value: 'Palau', countryCode: 'PW' },
  {
    label: 'Palestinian Territory, Occupied',
    value: 'Palestinian Territory, Occupied',
    countryCode: 'PS',
  },
  { label: 'Panama', value: 'Panama', countryCode: 'PA' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea', countryCode: 'PG' },
  { label: 'Paraguay', value: 'Paraguay', countryCode: 'PY' },
  { label: 'Peru', value: 'Peru', countryCode: 'PE' },
  { label: 'Philippines', value: 'Philippines', countryCode: 'PH' },
  { label: 'Pitcairn', value: 'Pitcairn', countryCode: 'PN' },
  { label: 'Poland', value: 'Poland', countryCode: 'PL' },
  { label: 'Portugal', value: 'Portugal', countryCode: 'PT' },
  { label: 'Puerto Rico', value: 'Puerto Rico', countryCode: 'PR' },
  { label: 'Qatar', value: 'Qatar', countryCode: 'QA' },
  { label: 'Reunion', value: 'Reunion', countryCode: 'RE' },
  { label: 'Romania', value: 'Romania', countryCode: 'RO' },
  {
    label: 'Russian Federation',
    value: 'Russian Federation',
    countryCode: 'RU',
  },
  { label: 'RWANDA', value: 'RWANDA', countryCode: 'RW' },
  { label: 'Saint Helena', value: 'Saint Helena', countryCode: 'SH' },
  {
    label: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
    countryCode: 'KN',
  },
  { label: 'Saint Lucia', value: 'Saint Lucia', countryCode: 'LC' },
  {
    label: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
    countryCode: 'PM',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
    countryCode: 'VC',
  },
  { label: 'Samoa', value: 'Samoa', countryCode: 'WS' },
  { label: 'San Marino', value: 'San Marino', countryCode: 'SM' },
  {
    label: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
    countryCode: 'ST',
  },
  { label: 'Saudi Arabia', value: 'Saudi Arabia', countryCode: 'SA' },
  { label: 'Senegal', value: 'Senegal', countryCode: 'SN' },
  {
    label: 'Serbia and Montenegro',
    value: 'Serbia and Montenegro',
    countryCode: 'CS',
  },
  { label: 'Seychelles', value: 'Seychelles', countryCode: 'SC' },
  { label: 'Sierra Leone', value: 'Sierra Leone', countryCode: 'SL' },
  { label: 'Singapore', value: 'Singapore', countryCode: 'SG' },
  { label: 'Slovakia', value: 'Slovakia', countryCode: 'SK' },
  { label: 'Slovenia', value: 'Slovenia', countryCode: 'SI' },
  { label: 'Solomon Islands', value: 'Solomon Islands', countryCode: 'SB' },
  { label: 'Somalia', value: 'Somalia', countryCode: 'SO' },
  { label: 'South Africa', value: 'South Africa', countryCode: 'ZA' },
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
    countryCode: 'GS',
  },
  { label: 'Spain', value: 'Spain', countryCode: 'ES' },
  { label: 'Sri Lanka', value: 'Sri Lanka', countryCode: 'LK' },
  { label: 'Sudan', value: 'Sudan', countryCode: 'SD' },
  { label: 'Suriname', value: 'Suriname', countryCode: 'SR' },
  {
    label: 'Svalbard and Jan Mayen',
    value: 'Svalbard and Jan Mayen',
    countryCode: 'SJ',
  },
  { label: 'Swaziland', value: 'Swaziland', countryCode: 'SZ' },
  { label: 'Sweden', value: 'Sweden', countryCode: 'SE' },
  { label: 'Switzerland', value: 'Switzerland', countryCode: 'CH' },
  {
    label: 'Syrian Arab Republic',
    value: 'Syrian Arab Republic',
    countryCode: 'SY',
  },
  {
    label: 'Taiwan, Province of China',
    value: 'Taiwan, Province of China',
    countryCode: 'TW',
  },
  { label: 'Tajikistan', value: 'Tajikistan', countryCode: 'TJ' },
  {
    label: 'Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
    countryCode: 'TZ',
  },
  { label: 'Thailand', value: 'Thailand', countryCode: 'TH' },
  { label: 'Timor-Leste', value: 'Timor-Leste', countryCode: 'TL' },
  { label: 'Togo', value: 'Togo', countryCode: 'TG' },
  { label: 'Tokelau', value: 'Tokelau', countryCode: 'TK' },
  { label: 'Tonga', value: 'Tonga', countryCode: 'TO' },
  {
    label: 'Trinidad and Tobago',
    value: 'Trinidad and Tobago',
    countryCode: 'TT',
  },
  { label: 'Tunisia', value: 'Tunisia', countryCode: 'TN' },
  { label: 'Turkey', value: 'Turkey', countryCode: 'TR' },
  { label: 'Turkmenistan', value: 'Turkmenistan', countryCode: 'TM' },
  {
    label: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
    countryCode: 'TC',
  },
  { label: 'Tuvalu', value: 'Tuvalu', countryCode: 'TV' },
  { label: 'Uganda', value: 'Uganda', countryCode: 'UG' },
  { label: 'Ukraine', value: 'Ukraine', countryCode: 'UA' },
  {
    label: 'United Arab Emirates',
    value: 'United Arab Emirates',
    countryCode: 'AE',
  },
  { label: 'United Kingdom', value: 'United Kingdom', countryCode: 'GB' },
  { label: 'United States', value: 'United States', countryCode: 'US' },
  {
    label: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
    countryCode: 'UM',
  },
  { label: 'Uruguay', value: 'Uruguay', countryCode: 'UY' },
  { label: 'Uzbekistan', value: 'Uzbekistan', countryCode: 'UZ' },
  { label: 'Vanuatu', value: 'Vanuatu', countryCode: 'VU' },
  { label: 'Venezuela', value: 'Venezuela', countryCode: 'VE' },
  { label: 'Viet Nam', value: 'Viet Nam', countryCode: 'VN' },
  {
    label: 'Virgin Islands, British',
    value: 'Virgin Islands, British',
    countryCode: 'VG',
  },
  {
    label: 'Virgin Islands, U.S.',
    value: 'Virgin Islands, U.S.',
    countryCode: 'VI',
  },
  { label: 'Wallis and Futuna', value: 'Wallis and Futuna', countryCode: 'WF' },
  { label: 'Western Sahara', value: 'Western Sahara', countryCode: 'EH' },
  { label: 'Yemen', value: 'Yemen', countryCode: 'YE' },
  { label: 'Zambia', value: 'Zambia', countryCode: 'ZM' },
  { label: 'Zimbabwe', value: 'Zimbabwe', countryCode: 'ZW' },
];
